<div class="wrap correios-vendor-generate" style="max-width: 600px; margin: 20px auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px; background-color: #f9f9f9; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
    <h1 style="font-size: 24px; color: #333;"><?php _e('Gerar Etiqueta de Envio', 'etiquetas-correios'); ?></h1>
    <p style="font-size: 16px; color: #555;"><?php _e('Você será direcionado ao site dos Correios para gerar sua etiqueta. Faça login utilizando as credenciais fornecidas no bookmarklet abaixo.', 'etiquetas-correios'); ?></p>
    <p style="font-size: 16px; color: #555;"><?php _e('Após o login, clique em "Remetente" e depois em "Novo Remetente". Em seguida, adicione o destinatário clicando em "Novo Destinatário".', 'etiquetas-correios'); ?></p>
    <p style="font-size: 16px; color: #555;"><?php _e('Os pacotes para a geração de etiquetas a serem escolhidos são 03298 - PAC CONTRATO AG para PAC e 03220 - SEDEX CONTRATO AG para SEDEX no campo Solicitar faixa de etiquetas.', 'etiquetas-correios'); ?></p>

    <p><strong><?php _e('Para preencher automaticamente seu usuário e senha no site dos Correios, arraste o bookmarklet abaixo para a barra de favoritos:', 'etiquetas-correios'); ?></strong></p>
    <a id="bookmarklet-link" href="javascript:(function(){document.getElementById('username').value='<?php echo esc_attr(get_option('etiquetas_correios_username')); ?>';document.getElementById('password').value='<?php echo esc_attr(get_option('etiquetas_correios_password')); ?>';})()" style="display: inline-block; background-color: #0073aa; color: white; padding: 10px 15px; text-decoration: none; border-radius: 5px;"><?php _e('Preencher Usuário e Senha', 'etiquetas-correios'); ?></a>
    <p style="font-size: 16px; color: #555;"><?php _e('Após abrir o site dos Correios, clique em "Adicionar bookmarklet" nas barras dos favoritos.', 'etiquetas-correios'); ?></p>

    <a href="https://cas.correios.com.br/login?service=https%3A%2F%2Fprepostagem.correios.com.br%2Flogin%2Fcas" target="_blank" style="display: inline-block; padding: 12px 20px; background-color: #0073aa; color: white; border-radius: 5px; text-decoration: none; font-size: 16px; margin-right: 10px; text-align: center; box-shadow: 0 4px 6px rgba(0, 115, 170, 0.3); transition: background-color 0.3s ease;"><?php _e('Gerar Etiquetas no site dos Correios', 'etiquetas-correios'); ?></a>
    <a href="<?php echo wcfm_get_endpoint_url('store-manager'); ?>" style="display: inline-block; padding: 12px 20px; background-color: #f44336; color: white; border-radius: 5px; text-decoration: none; font-size: 16px; text-align: center; box-shadow: 0 4px 6px rgba(244, 67, 54, 0.3); transition: background-color 0.3s ease;"><?php _e('Voltar ao Store Manager', 'etiquetas-correios'); ?></a>
</div>
